// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SantaSecilia.Infrastructure.Data;

#nullable disable

namespace SantaSecilia.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221064604_SimplifiedDatabase")]
    partial class SimplifiedDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SantaSecilia.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deactivated_at");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT")
                        .HasColumnName("hourly_rate");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.DailyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("work_date");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId", "WorkDate");

                    b.ToTable("daily_records", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.DailyRecordLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activity_id");

                    b.Property<int>("DailyRecordId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("daily_record_id");

                    b.Property<int>("Hours")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hours");

                    b.Property<int>("LotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lot_id");

                    b.Property<decimal>("RateSnapshot")
                        .HasColumnType("TEXT")
                        .HasColumnName("rate_snapshot");

                    b.Property<decimal>("SubtotalSnapshot")
                        .HasColumnType("TEXT")
                        .HasColumnName("subtotal_snapshot");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("LotId");

                    b.HasIndex("DailyRecordId", "ActivityId", "LotId");

                    b.ToTable("daily_record_lines", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deactivated_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("lots", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.WeeklyPayStub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EducationInsuranceDeduction")
                        .HasColumnType("TEXT")
                        .HasColumnName("education_insurance_deduction");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("generated_at");

                    b.Property<decimal>("GrossEarnings")
                        .HasColumnType("TEXT")
                        .HasColumnName("gross_earnings");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("net_pay");

                    b.Property<string>("PdfPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("pdf_path");

                    b.Property<decimal>("SocialSecurityDeduction")
                        .HasColumnType("TEXT")
                        .HasColumnName("social_security_deduction");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("TEXT")
                        .HasColumnName("total_deductions");

                    b.Property<int>("TotalHours")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_hours");

                    b.Property<decimal>("UnionDues")
                        .HasColumnType("TEXT")
                        .HasColumnName("union_dues");

                    b.Property<DateOnly>("WeekEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("week_end");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("week_start");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.HasIndex("WeekStart", "WeekEnd", "WorkerId")
                        .IsUnique();

                    b.ToTable("weekly_pay_stubs", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("identification_number");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique();

                    b.ToTable("workers", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.DailyRecord", b =>
                {
                    b.HasOne("SantaSecilia.Domain.Entities.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.DailyRecordLine", b =>
                {
                    b.HasOne("SantaSecilia.Domain.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaSecilia.Domain.Entities.DailyRecord", "DailyRecord")
                        .WithMany("Lines")
                        .HasForeignKey("DailyRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantaSecilia.Domain.Entities.Lot", "Lot")
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("DailyRecord");

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.WeeklyPayStub", b =>
                {
                    b.HasOne("SantaSecilia.Domain.Entities.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.DailyRecord", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
