// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SantaSecilia.Infrastructure.Data;

#nullable disable

namespace SantaSecilia.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219034734_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SantaSecilia.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deactivated_at");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT")
                        .HasColumnName("hourly_rate");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entity_id");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entity_type_id");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.DailyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activity_id");

                    b.Property<bool>("AllowDuplicate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_duplicate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("Hours")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hours");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<int>("LotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lot_id");

                    b.Property<decimal>("RateSnapshot")
                        .HasColumnType("TEXT")
                        .HasColumnName("rate_snapshot");

                    b.Property<decimal>("SubtotalSnapshot")
                        .HasColumnType("TEXT")
                        .HasColumnName("subtotal_snapshot");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_by_user_id");

                    b.Property<int?>("WeeklyClosingId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weekly_closing_id");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("work_date");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LotId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("WeeklyClosingId");

                    b.HasIndex("WorkerId", "WorkDate");

                    b.HasIndex("WorkerId", "WorkDate", "ActivityId", "LotId");

                    b.ToTable("daily_records", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.EntityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("entity_types", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deactivated_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("lots", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.PayStubLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<int>("DailyRecordId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("daily_record_id");

                    b.Property<int>("PayStubId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pay_stub_id");

                    b.HasKey("Id");

                    b.HasIndex("DailyRecordId");

                    b.HasIndex("PayStubId");

                    b.ToTable("pay_stub_lines", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.RecordVoiding", b =>
                {
                    b.Property<int>("RecordId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("record_id");

                    b.Property<string>("VoidReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("void_reason");

                    b.Property<DateTime>("VoidedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("voided_at");

                    b.Property<int>("VoidedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("voided_by_user_id");

                    b.HasKey("RecordId");

                    b.HasIndex("VoidedByUserId");

                    b.ToTable("record_voidings", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.WeeklyClosing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<decimal>("SeRateSnapshot")
                        .HasColumnType("TEXT")
                        .HasColumnName("se_rate_snapshot");

                    b.Property<decimal>("SsRateSnapshot")
                        .HasColumnType("TEXT")
                        .HasColumnName("ss_rate_snapshot");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<decimal>("UnionDuesSnapshot")
                        .HasColumnType("TEXT")
                        .HasColumnName("union_dues_snapshot");

                    b.Property<DateOnly>("WeekEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("week_end");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("week_start");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("WeekStart", "WeekEnd")
                        .IsUnique();

                    b.ToTable("weekly_closings", null, t =>
                        {
                            t.HasCheckConstraint("ck_weekly_closings_status", "status IN ('CLOSED', 'VOIDED')");
                        });
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.WeeklyPayStub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("generated_at");

                    b.Property<decimal>("GrossEarnings")
                        .HasColumnType("TEXT")
                        .HasColumnName("gross_earnings");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("net_pay");

                    b.Property<string>("PdfPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("pdf_path");

                    b.Property<decimal>("SeDeduction")
                        .HasColumnType("TEXT")
                        .HasColumnName("se_deduction");

                    b.Property<decimal>("SsDeduction")
                        .HasColumnType("TEXT")
                        .HasColumnName("ss_deduction");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("TEXT")
                        .HasColumnName("total_deductions");

                    b.Property<int>("TotalHours")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_hours");

                    b.Property<decimal>("UnionDues")
                        .HasColumnType("TEXT")
                        .HasColumnName("union_dues");

                    b.Property<int>("WeeklyClosingId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weekly_closing_id");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.HasIndex("WeeklyClosingId", "WorkerId")
                        .IsUnique();

                    b.ToTable("weekly_pay_stubs", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("id_number");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdNumber")
                        .IsUnique();

                    b.ToTable("workers", (string)null);
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.AuditEvent", b =>
                {
                    b.HasOne("SantaSecilia.Domain.Entities.EntityType", "EntityType")
                        .WithMany("AuditEvents")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaSecilia.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntityType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.DailyRecord", b =>
                {
                    b.HasOne("SantaSecilia.Domain.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaSecilia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaSecilia.Domain.Entities.Lot", "Lot")
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaSecilia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SantaSecilia.Domain.Entities.WeeklyClosing", null)
                        .WithMany()
                        .HasForeignKey("WeeklyClosingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SantaSecilia.Domain.Entities.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Lot");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.PayStubLine", b =>
                {
                    b.HasOne("SantaSecilia.Domain.Entities.DailyRecord", "DailyRecord")
                        .WithMany()
                        .HasForeignKey("DailyRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaSecilia.Domain.Entities.WeeklyPayStub", "PayStub")
                        .WithMany("Lines")
                        .HasForeignKey("PayStubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyRecord");

                    b.Navigation("PayStub");
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.RecordVoiding", b =>
                {
                    b.HasOne("SantaSecilia.Domain.Entities.DailyRecord", "Record")
                        .WithOne("Voiding")
                        .HasForeignKey("SantaSecilia.Domain.Entities.RecordVoiding", "RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantaSecilia.Domain.Entities.User", "VoidedByUser")
                        .WithMany()
                        .HasForeignKey("VoidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Record");

                    b.Navigation("VoidedByUser");
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.WeeklyClosing", b =>
                {
                    b.HasOne("SantaSecilia.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.WeeklyPayStub", b =>
                {
                    b.HasOne("SantaSecilia.Domain.Entities.WeeklyClosing", "WeeklyClosing")
                        .WithMany()
                        .HasForeignKey("WeeklyClosingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantaSecilia.Domain.Entities.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WeeklyClosing");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.DailyRecord", b =>
                {
                    b.Navigation("Voiding");
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.EntityType", b =>
                {
                    b.Navigation("AuditEvents");
                });

            modelBuilder.Entity("SantaSecilia.Domain.Entities.WeeklyPayStub", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
